# Generated by Django 5.1.13 on 2025-10-04 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinDailyValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('usd_max_value', models.FloatField(max_length=12)),
                ('usd_min_value', models.FloatField(max_length=12)),
                ('usd_avg_value', models.FloatField(max_length=12)),
                ('ars_max_value', models.FloatField(max_length=12)),
                ('ars_min_value', models.FloatField(max_length=12)),
                ('ars_avg_value', models.FloatField(max_length=12)),
            ],
            options={
                'db_table': 'bitcoin_daily_values',
                'ordering': ['-created'],
                'abstract': False,
                'indexes': [models.Index(condition=models.Q(('created__gte', datetime.date(2025, 7, 6))), fields=['created'], name='bitcoin_created_index')],
            },
        ),
        migrations.CreateModel(
            name='EthereumDailyValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('usd_max_value', models.FloatField(max_length=12)),
                ('usd_min_value', models.FloatField(max_length=12)),
                ('usd_avg_value', models.FloatField(max_length=12)),
                ('ars_max_value', models.FloatField(max_length=12)),
                ('ars_min_value', models.FloatField(max_length=12)),
                ('ars_avg_value', models.FloatField(max_length=12)),
            ],
            options={
                'db_table': 'ethereum_daily_values',
                'ordering': ['-created'],
                'abstract': False,
                'indexes': [models.Index(condition=models.Q(('created__gte', datetime.date(2025, 7, 6))), fields=['created'], name='ethereum_created_index')],
            },
        ),
    ]
