# Generated by Django 5.1.13 on 2025-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_values', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoindailyvalues',
            name='ars_avg_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bitcoindailyvalues',
            name='ars_max_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bitcoindailyvalues',
            name='ars_min_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bitcoindailyvalues',
            name='usd_avg_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bitcoindailyvalues',
            name='usd_max_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bitcoindailyvalues',
            name='usd_min_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ethereumdailyvalues',
            name='ars_avg_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ethereumdailyvalues',
            name='ars_max_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ethereumdailyvalues',
            name='ars_min_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ethereumdailyvalues',
            name='usd_avg_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ethereumdailyvalues',
            name='usd_max_value',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ethereumdailyvalues',
            name='usd_min_value',
            field=models.FloatField(max_length=20),
        ),
    ]
