# Generated by Django 5.1.13 on 2025-10-05 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_values', '0002_alter_bitcoindailyvalues_ars_avg_value_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bitcoindailyvalues',
            name='bitcoin_created_index',
        ),
        migrations.RemoveIndex(
            model_name='ethereumdailyvalues',
            name='ethereum_created_index',
        ),
        migrations.AddIndex(
            model_name='bitcoindailyvalues',
            index=models.Index(condition=models.Q(('created__gte', datetime.date(2025, 7, 7))), fields=['created'], name='bitcoin_created_index'),
        ),
        migrations.AddIndex(
            model_name='ethereumdailyvalues',
            index=models.Index(condition=models.Q(('created__gte', datetime.date(2025, 7, 7))), fields=['created'], name='ethereum_created_index'),
        ),
    ]
