# Generated by Django 5.1.13 on 2025-10-07 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_values', '0004_remove_bitcoindailyvalues_bitcoin_created_index_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bitcoindailyvalues',
            name='bitcoin_created_index',
        ),
        migrations.RemoveIndex(
            model_name='ethereumdailyvalues',
            name='ethereum_created_index',
        ),
        migrations.AddField(
            model_name='bitcoindailyvalues',
            name='ars_avg_24h_vol',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoindailyvalues',
            name='ars_avg_market_cap',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoindailyvalues',
            name='usd_avg_24h_vol',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoindailyvalues',
            name='usd_avg_market_cap',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethereumdailyvalues',
            name='ars_avg_24h_vol',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethereumdailyvalues',
            name='ars_avg_market_cap',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethereumdailyvalues',
            name='usd_avg_24h_vol',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethereumdailyvalues',
            name='usd_avg_market_cap',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='bitcoindailyvalues',
            index=models.Index(condition=models.Q(('created__gte', datetime.date(2025, 7, 9))), fields=['created'], name='bitcoin_created_index'),
        ),
        migrations.AddIndex(
            model_name='ethereumdailyvalues',
            index=models.Index(condition=models.Q(('created__gte', datetime.date(2025, 7, 9))), fields=['created'], name='ethereum_created_index'),
        ),
    ]
