# Generated by Django 5.1.13 on 2025-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_values', '0005_remove_bitcoindailyvalues_bitcoin_created_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoindailyvalues',
            name='ars_avg_24h_vol',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bitcoindailyvalues',
            name='ars_avg_market_cap',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bitcoindailyvalues',
            name='usd_avg_24h_vol',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bitcoindailyvalues',
            name='usd_avg_market_cap',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ethereumdailyvalues',
            name='ars_avg_24h_vol',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ethereumdailyvalues',
            name='ars_avg_market_cap',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ethereumdailyvalues',
            name='usd_avg_24h_vol',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ethereumdailyvalues',
            name='usd_avg_market_cap',
            field=models.FloatField(max_length=25),
        ),
    ]
